locations = ['Saint Bon',
             'Navigli',
             'Bicocca',
             'Rho']


exams = ['Angio-RM dist. vasc. intracran.',
         'Colangio Rm',
         'RM Massiccio facciale',
         'RM Orbite',
         'RM Rinofaringe',
         'RM Rocche Petrose',
         'RM Sella Turcica',
         'RM articolazione temp.mand.b.',
         'RM artic.temporo-mandibolare-m',
         'RM massiccio facciale S/C co.',
         'RM orbite S/C co.',
         'RM sella turcica s/c co.',
         'RM rinofaringe s/c co.',
         'RM rocche petrose s/c co.',
         'RM cervello, tronco encefalico',
         'RM cervello, tronco encefalico per deficit cognitivo',
         'RM cervello,tronco enc.s/c co.',
         'RM del torace - pediatria',
         'RM del Torace',
         'RM del torace S/C co.',
         'Angio Rm del distretto toracico',
         'RM del Cuore',
         'RM del cuore s/c co.',
         'RM cuore da stress',
         'Angio Rm vasi del collo',
         'RM del Collo',
         'RM del Collo-rinofaringe',
         'RM del collo S/C co.',
         'RM del collo piu massiccio facciale s/c contrasto',
         'RM del collo pi� massiccio facciale s/c contrasto',
         'Rm tratto cervicale s/c con co',
         'RM tratto cervicale',
         'MOC vertebrale',
         'Rm tratto dorsale s/c con co',
         'RM tratto dorsale',
         'RM Rachide <2 Tratti>',
         'RM Rachide in Toto',
         'RM rachide <2 tratti> s/c co.',
         'RM rachide in toto S/C co.',
         'RM tratto lombare',
         'RM tratto lombare s/c con co',
         'Rm bacino',
         'Angio Rm addome inferiore',    
         'Angio Rm addome superiore',
         'RM Addome Superiore',
         'RM addome superiore s/c contr',
         'RM addome com.scavo pel.S/C co',
         'RM addome com.scavo pelvico',
         'RM addome inf.pelv.con st.funz.',
         'RM addome inf.scavo pel.S/C co',
         'RM addome inf.scavo pelvico',
         'RM addome superiore + inferiore scavo pelvico s/c contrasto',
         'Entero rm con e senza contrasto',
         'RM mammella',
         'RM mammella s/c contrasto',
         'RM multiparametrica prostata S/C contrasto',
         'RM multiparametrica prostata S/C contrasto (RMNPRS)',
         'RM polso-mano', 
         'RM gomito-avambraccio',
         'RM Spalla',
         'Artro RM spalla',
         'MOC femorale',
         'RM ginocchio',
         'Rm ginocchio pediatrica',
         'Angio Rm arto sup. o inf.',
         'RM Articolazioni',
         'Artro RM articolare',
         'RM artic.seg.osseo aggiuntivo',
         'MOC Multipla',
         'Pacchetto MOC + Vit D25',
         'RM organo distr.o appar.agg.',
         'RM segmento aggiuntivo',
         'RM Muscoloscheletrica',
         'RM muscoloscheletrica S/C co.',
         'RM muscoloscheletrica pediatr.' 
         ]

priorities = ['U', 'S', 'D', 'P']

payment_methods = ['S.S.N.',
                   'Fondi Plus',
                   'Solventi assimilati',
                   'CDI check']

fiscal_code_pattern = "^[A-Z]{6}[A-Z0-9]{2}[A-Z][A-Z0-9]{2}[A-Z][A-Z0-9]{3}[A-Z]$"